export const IS_ERROR_CHANGE = 'IS_ERROR_CHANGE';
export const ERROR_CHANGE = 'ERROR_CHANGE';
export const SELECTED_EVENT_CHANGE = 'SELECTED_EVENT_CHANGE';
export const SELECTED_MEMBER_CHANGE = 'SELECTED_MEMBER_CHANGE';
export const ALL_EVENTS = 'ALL_EVENTS';
export const ALL_MEMBERS = 'ALL_MEMBERS';
